myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    path(r'<int:topic_id>/', views.detail, name='detail'),
    path(r'findcourses/', views.findcourses, name='findcourses'),
    path(r'place_order/', views.place_order, name='place_order'),
    path(r'review/', views.review_view, name='review'),
    path(r'login/', views.user_login, name='login'),
    path(r'logout/', views.user_logout, name='logout'),
    path(r'myaccount/', views.myaccount, name='myaccount'),
    path(r'myorders/', views.myorders, name='myorders'),
    path(r'register/', views.register, name='register'),
]

mysite20/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from myapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
]

myapp/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from django import forms
from django.db import models
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


# Create your models here.


class Topic(models.Model):
    name = models.CharField(max_length=200)
    length = models.IntegerField(default=12)

    def __str__(self):
        return self.name + ' [ ' + str(self.length) + ' Week ]'


class Course(models.Model):
    title = models.CharField(max_length=200)
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                validators=[MinValueValidator(50), MaxValueValidator(500)])
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(blank=True)
    num_reviews = models.PositiveIntegerField(default=0)

    def __str__(self):
        return '[id: ' + str(self.id) + ' ] ' + self.title + '  | # of reviews: ' + str(self.num_reviews)


class Student(User):
    LVL_CHOICES = [
        ('HS', 'High School'),
        ('UG', 'Undergraduate'),
        ('PG', 'Postgraduate'),
        ('ND', 'No Degree'),
    ]

    level = models.CharField(choices=LVL_CHOICES, max_length=2, default='HS')
    address = models.CharField(max_length=300)
    province = models.CharField(max_length=2, default='ON')
    registered_courses = models.ManyToManyField(Course, blank=True)
    interested_in = models.ManyToManyField(Topic)
    profile_picture = models.ImageField(verbose_name="Profile Picture", default="static/myapp/profilepic.png", upload_to="",
                                        blank=True)

    def __str__(self):
        return self.username + ' | ' + self.first_name + ' ' + self.last_name


class Order(models.Model):
    courses = models.ManyToManyField(Course)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    ORDER_STS_CHOICES = [
        (0, 'Cancelled'),
        (1, 'Confirmed'),
        (2, 'On Hold'),
    ]
    order_status = models.IntegerField(choices=ORDER_STS_CHOICES, default=1)
    order_date = models.DateField(default=timezone.now)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def total_cost(self):
        total = 0
        courses = self.student.registered_courses.all()
        for course in courses:
            total += course.price
        return total

    def total_items(self):
        total = 0
        courses = self.student.registered_courses.all()
        for course in courses:
            total += 1
        return total

    def __str__(self):
        return self.student.username + ' | ' + self.student.last_name + ', ' + self.student.first_name


class Review(models.Model):
    reviewer = models.EmailField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comments = models.TextField(blank=True)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.reviewer + ' rated ' + self.rating + ' to ' + self.course.title

# class OrderAdmin(models.Model):

myapp/forms.py
from django import forms
from myapp.models import Order, Review, Student


class SearchForm(forms.Form):
    LENGTH_CHOICES = [
        (8, '8 Weeks'),
        (10, '10 Weeks'),
        (12, '12 Weeks'),
        (14, '14 Weeks'),
    ]
    name = forms.CharField(max_length=100, required=False, label='Student Name')
    length = forms.TypedChoiceField(widget=forms.RadioSelect, choices=LENGTH_CHOICES, coerce=int, required=False,
                                    label='Preferred course duration:')
    max_price = forms.IntegerField(required=True, label='Maximum Price', min_value=0)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['courses', 'student', 'order_status']
        widgets = {'courses': forms.CheckboxSelectMultiple(), 'order_type': forms.RadioSelect}
        labels = {'student': u'Student Name', }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['reviewer', 'course', 'rating', 'comments']
        widgets = {'course': forms.RadioSelect}
        labels = {'reviewer': 'please enter a valid Email', 'rating': 'Rating: An integer between 1 (worst) and 5 ('
                                                                      'best)', }


class RegisterForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['username', 'first_name', 'last_name', 'email', 'level', 'address', 'province', 'registered_courses',
                  'interested_in']
        widgets = {'email': forms.EmailInput, 'level': forms.RadioSelect,
                   'registered_courses': forms.CheckboxSelectMultiple(),
                   'interested_in': forms.CheckboxSelectMultiple()}
        # , 'registered_courses': forms.CheckboxSelectMultiple(), 'interested_in': forms.CheckboxSelectMultiple()}
        # labels = [le]

myapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
# Import necessary classes
from datetime import *
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from .models import Topic, Course, Student, Order
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from .forms import SearchForm, OrderForm, ReviewForm, RegisterForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test


# Create your views here.

def index(request):
    if request.session.get('last_login'):
        last_login = request.session['last_login']
    else:
        last_login = "Your last login was more than one hour ago"
    top_list = Topic.objects.all().order_by('id')[:10]
    return render(request, 'myapp/index.html', {'top_list': top_list, 'last_login': last_login})


def about(request):
    if request.session.get('about_visits'):
        about_visits_number = request.session['about_visits']
        about_visits_number += 1
        request.session['about_visits'] = about_visits_number
        request.session.set_expiry(300)
    else:
        request.session['about_visits'] = 1
        request.session.set_expiry(300)

    about_visits_number = request.session['about_visits']
    about_message = 'This is an E-learning Website! Search our Topics to find all available Courses.'
    return render(request, 'myapp/about.html', {'about_message': about_message, 'visits_number': about_visits_number})


def detail(request, topic_id):
    topic = get_object_or_404(Topic, pk=topic_id)
    related_courses = Course.objects.filter(topic=topic_id)
    return render(request, 'myapp/detail.html',
                  {'topic_id': topic_id, 'topic': topic, 'related_courses': related_courses})


def findcourses(request):
    form = SearchForm(request.POST)
    if form.is_valid():
        name = form.cleaned_data['name']
        length = form.cleaned_data['length']
        max_price = form.cleaned_data['max_price']
        if length:
            topics = Topic.objects.filter(length=length)
        else:
            topics = Topic.objects.all()
        courselist = []
        for top in topics:
            for course in list(top.courses.all()):

                if course.price <= max_price:
                    courselist.append(str(course.title))

        return render(request, 'myapp/results.html',
                      {'courselist': courselist, 'name': name, 'length': length, 'max_price': max_price})
    else:
        return HttpResponse('Invalid data')
        form = SearchForm()
        return render(request, 'myapp/findcourses.html', {'form': form})


def place_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            courses = form.cleaned_data['courses']
            order = form.save(commit=False)
            student = order.student
            status = order.order_status
            order.save()
            if status == 1:
                for c in courses.all():
                    student.registered_courses.add(c)
            return render(request, 'myapp/order_response.html', {'courses': courses, 'order': order})
        else:
            return render(request, 'myapp/place_order.html', {'form': form})

    else:
        form = OrderForm()
        return render(request, 'myapp/place_order.html', {'form': form})


def review_view(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=True)
            rating = form.cleaned_data['rating']
            course = form.cleaned_data['course']
            review.save()

            if 1 <= rating <= 5:
                course.num_reviews += 1
                course.save()
                top_list = Topic.objects.all().order_by('id')
                error_message = 'Thank you for reviewing the course: ' + str(course.title) + '!'
                return render(request, 'myapp/review.html', {'form': form, 'error_message': error_message})
            else:
                form = ReviewForm()
                error_message = 'You must enter a rating between 1 and 5!'
                return render(request, 'myapp/review.html', {'form': form, 'error_message': error_message})
    else:
        form = ReviewForm()
        return render(request, 'myapp/review.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        current_login = datetime.now()
        username = request.POST['username']
        password = request.POST['password']
        next = request.POST['next']
        print("NEXT VALUE: " + str(request.POST['next']) + str(type(request.POST['next'])))
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                # response.set_cookie('last_login', str(current_login), max_age=6000)
                request.session['last_login'] = str(current_login)
                request.session.set_expiry(6000)
                # return HttpResponse(reverse('myapp:index'))
                # print(get_redirect_field_name())
                if next == 'None':
                    print("redirecting to home: " + str(reverse('myapp:index')))
                    print(str(request.POST['next']))
                    return HttpResponseRedirect(reverse('myapp:index'))
                else:
                    print("redirecting to next: " + str(next))
                    # return redirect(request.GET.get('/myapp/', next))
                    print("it reaches here ______")
                    return redirect(next)
                # return redirect(request.GET.get('next'))
                # return render(request, 'myapp/index.html')

            else:
                return render(request, 'myapp/login.html', {'error_message': 'Your account is disabled.'})
        else:
            return render(request, 'myapp/login.html', {'error_message': 'Invalid login details.'})
    else:
        next = request.GET.get('next')
        request.session['next'] = request.GET.get('next', '/')
        print(next)
        return render(request, 'myapp/login.html', {'next': str(next)})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))


@login_required(login_url='/myapp/login/')
def myaccount(request):
    if request.method == 'GET':
        username = request.user.username
        print(username)
        try:
            student = Student.objects.get(username=username)
            first_name = student.first_name
            last_name = student.last_name
            interested_in = student.interested_in
            registered_courses = student.registered_courses
            profile_picture_url = student.profile_picture.url
            print(profile_picture_url)
            topic_list = []
            for topic in interested_in.all():
                topic_list.append(topic)
            course_list = []
            for course in registered_courses.all():
                course_list.append(course)
            return render(request, 'myapp/myaccount.html',
                          {'first_name': first_name, 'last_name': last_name, 'topic_list': topic_list,
                           'course_list': course_list, 'profile_picture_url': profile_picture_url})
        except Student.DoesNotExist:
            return render(request, 'myapp/register.html', {'error_message': 'You are not a registered student!'})
    else:
        return render(request, 'myapp/login.html', {'error_message': 'You are not logged in!'})


@login_required(login_url='/myapp/login/')
def myorders(request):
    if request.method == 'GET':
        username = request.user.username
        print(username)
        try:
            student = Student.objects.get(username=username)
            print(student)
            first_name = student.first_name
            last_name = student.last_name
            student_fullname = {
                'first_name': str(student.first_name),
                'last_name': str(student.last_name)
            }

            order_list = []
            orders = Order.objects.filter(student=student)
            print(orders)
            for order in orders:
                record = [order.id, order.order_date, order.order_status, order.total_items()]
                order_list.append(record)

            print(order_list)
            return render(request, 'myapp/myorders.html', {'student': student_fullname, 'order_list': order_list})

        except Student.DoesNotExist:
            return render(request, 'myapp/register.html', {'error_message': 'You are not a registered student!'})
    else:
        return render(request, 'myapp/login.html', {'error_message': 'You are not logged in!'})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            level = form.cleaned_data['level']
            address = form.cleaned_data['address']
            province = form.cleaned_data['province']
            registered_courses = form.cleaned_data['registered_courses']
            interested_in = form.cleaned_data['interested_in']
            student = form.save(commit=False)
            # student = order.student
            # status = order.order_status
            student.save()
            # if status == 1:
            #     for c in courses.all():
            #         student.registered_courses.add(c)
            topic_list = []
            for topic in interested_in.all():

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if about_message %}
        <h3>
            {{ about_message }}
        </h3>
    {% else %}
        <strong>There are no available content!</strong>
    {% endif %}
    {% if visits_number %}
        <p># of visits: {{ visits_number }}</p>
    {% else %}
        <p>No # of visits available</p>
    {% endif %}
{% endblock %}
{% block title %}
    eLearning - APP About page
{% endblock %}

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
</head>
<body>
<div class="text-center">
    {% if error_message %}
        <h3>{{ error_message }}</h3>
    {% endif %}
    {% if request.user.username %}
        <p>Hi, {{ request.user.first_name }} | <a href="{% url 'myapp:logout' %}">Logout</a> | <a
                href="{% url 'myapp:myaccount' %}">My Account</a> | <a href="{% url 'myapp:myorders' %}">My Orders</a>
        </p>
    {% else %}
        <p><a href="{% url 'myapp:login' %}">You can LOGIN here</a> | <a href="{% url 'myapp:register' %}">You can
            REGISTER here</a></p>
    {% endif %}

    {% block myhdg %}
    {% endblock %}

    {% block body_block %}*** {% endblock %}
</div>
<hr/>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-3"><a href="{% url 'myapp:about' %}">Find out about this site</a></div>
        <div class="col-3"><a href="{% url 'myapp:index' %}">Click here to return to main page</a></div>
        <div class="col-3"><a href="{% url 'myapp:findcourses' %}">Click here to search course(s)</a></div>
        <div class="col-3"><a href="{% url 'myapp:review' %}">Course Review Page</a></div>
    </div>
</div>
</body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if topic_id %}
        <h2>
            Topic id: {{ topic_id }} | Topic Name: {{ topic.name }} | Length: {{ topic.length }} weeks


        </h2>
    {% else %}
        <strong>There are no available topic with this id!</strong>
    {% endif %}
    {% if related_courses %}
        <ol>
            {% for course  in related_courses %}
                <li> {{ course }} </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no related coursed for this topic!</strong>
    {% endif %}
{% endblock %}

myapp/templates/myapp/findcourses.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:findcourses' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit1" value="Find Courses"/>
    </form>

{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if last_login %}
        <h4>Your last login were at: {{ last_login }}</h4>
    {% else %}

    {% endif %}
    {% if top_list %}
        <h2>List of Topics</h2>
        <ol>
            {% for top  in top_list %}
                <li><a href="{% url 'myapp:detail' top.pk %}">{{ top.name }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
    <h2>You can Order from here</h2>
    <a href="{% url 'myapp:place_order' %}">Place Your Order here!</a>
{% endblock %}

myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:login' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <input type='text' name="username"/>
        <input type='password' name="password"/>
        <input type="submit" name="login" value="Login" />
    </form>
{% endblock %}

myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if error_message %}
        <h3>{{ error_message }}</h3>
    {% endif %}
    {% if profile_picture_url %}
        <img src="/static/myapp{{ profile_picture_url }}" alt="profile picture of {{ first_name }}">
    {% endif %}
    {% if first_name and last_name %}
        <h3>Student Name: {{ first_name }} {{ last_name }}</h3>
    {% endif %}
        <h2>Interested Topics</h2>

    <ol>
        {% for topic in topic_list %}
            <li>
        {{ topic }}
            </li>
        {% endfor %}
    </ol>
<h2>Registered Courses</h2>
<ol>
    {% for course in course_list %}
    <li>
        {{ course }}
    </li>
    {% endfor %}
</ol>


{% endblock body_block %}

myapp/templates/myapp/myorders.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if error_message %}
        <h3>{{ error_message }}</h3>
    {% endif %}
    {% if student %}
        <h3>Student Name: {{ student.first_name }} {{ student.last_name }}</h3>
    {% else %}
        <h3>User is not </h3>
    {% endif %}

    <h2>Submitted Orders</h2>
    {% if order_list %}
        <ol>
            {% for order in order_list reversed %}
                <li>
                    <ul>
                        <li>Order ID: {{ order.0 }}</li>
                        <li>Ordered Date: {{ order.1 }}</li>
                        <li>Order Status:
                            {% if order.2 == 0 %}
                                Cancelled
                            {% elif order.2 == 1 %}
                                Confirmed
                            {% elif order.2 == 2 %}
                                On Hold
                            {% endif %}
                        </li>
                        <li>Total Order Items: {{ order.3 }}</li>
                    </ul>
                </li>
            {% endfor %}
        </ol>
    {% else %}
        <h3> No order has been submitted!</h3>
    {% endif %}


{% endblock body_block %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block myhdg %}Hello {{ order.student }}{% endblock %}

{% block body_block %}
    {% if courses %}
        <ol>
            {% for course  in courses %}
                <li> {{ course }} </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no related coursed for this topic!</strong>
    {% endif %}

{% endblock %}

myapp/templates/myapp/place_order.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:place_order' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit1" value="Place an Order"/>
    </form>

{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit1" value="Register"/>
    </form>

{% endblock %}

myapp/templates/myapp/results.html
{% extends 'myapp/base.html' %}

{% block myhdg %}Hello {{ name }}{% endblock %}
{% block body_block %}
    {% if courselist %}
        <ol>
            {% for course  in courselist %}
                <li> {{ course }} </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no related course in this search!</strong>
    {% endif %}
{% endblock %}

myapp/templates/myapp/review.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if error_message %}
  <p>{{ error_message }}</p>
{% endif %}
    <form action="{% url 'myapp:review' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Submit Review" />
    </form>

{% endblock %}